version: "3.8"

services:
  bot:
    build: .
    depends-on:
      - postgres
    env_file:
      - .env
  postgres:
    image: "postgres:14-alpine"
    env_file: 
      - .env
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
