name: Style
on:
  pull_request:
jobs:
  build:
    name: Style check
    timeout-minutes: 360
    strategy:
      fail-fast: true
      matrix:
        NODE_VERSION:
          - 16
        OS:
          - ubuntu-latest
          # - windows-latest
          # - macos-latest
    runs-on: ${{ matrix.OS }}
    steps:
      - name: Git Checkout
        uses: actions/checkout@v2
      - name: Node.js Setup
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.NODE_VERSION }}
      - name: Dependencies installation
        run: yarn install
      - name: Style check
        run: yarn run lint
